### ISSUE TITLE
tikv build error on macos

### ISSUE THREAD

**Issue by zhouqiang-cl** [tikv/tikv#11823]
### What version of TiKV are you using?

```
[2022-01-08T14:58:43.802Z] error[E0605]: non-primitive cast: `NonZeroU64` as `u32`

[2022-01-08T14:58:43.802Z]    --> components/tikv_util/src/sys/thread.rs:210:9

[2022-01-08T14:58:43.802Z]     |

[2022-01-08T14:58:43.802Z] 210 |         std::thread::current().id().as_u64() as Pid

[2022-01-08T14:58:43.802Z]     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ an `as` expression can only be used to convert between primitive types or to coerce to a specific trait object

[2022-01-08T14:58:43.802Z] 

[2022-01-08T14:58:43.802Z] error[E0308]: mismatched types

[2022-01-08T14:58:43.802Z]    --> components/tikv_util/src/sys/thread.rs:214:12

[2022-01-08T14:58:43.802Z]     |

[2022-01-08T14:58:43.802Z] 213 |     pub fn thread_ids<C: FromIterator<Pid>>(pid: Pid) -> io::Result<C> {

[2022-01-08T14:58:43.802Z]     |                       - this type parameter

[2022-01-08T14:58:43.802Z] 214 |         Ok(Some(thread_id()))

[2022-01-08T14:58:43.802Z]     |            ^^^^^^^^^^^^^^^^^ expected type parameter `C`, found enum `std::option::Option`

[2022-01-08T14:58:43.802Z]     |

[2022-01-08T14:58:43.802Z]     = note: expected type parameter `C`

[2022-01-08T14:58:43.802Z]                          found enum `std::option::Option<u32>`

[2022-01-08T14:58:43.802Z] 

[2022-01-08T14:58:43.802Z] error[E0609]: no field `stime` on type `ThreadStat`

[2022-01-08T14:58:43.802Z]    --> components/tikv_util/src/sys/thread.rs:235:27

[2022-01-08T14:58:43.802Z]     |

[2022-01-08T14:58:43.802Z] 235 |         s_time: full_stat.stime as _,

[2022-01-08T14:58:43.802Z]     |                           ^^^^^ help: a field with a similar name exists: `s_time`

[2022-01-08T14:58:43.802Z] 

[2022-01-08T14:58:43.802Z] error[E0609]: no field `utime` on type `ThreadStat`

[2022-01-08T14:58:43.802Z]    --> components/tikv_util/src/sys/thread.rs:236:27

[2022-01-08T14:58:43.802Z]     |

[2022-01-08T14:58:43.802Z] 236 |         u_time: full_stat.utime as _,

[2022-01-08T14:58:43.802Z]     |                           ^^^^^ help: a field with a similar name exists: `u_time`

[2022-01-08T14:58:43.802Z] 

[2022-01-08T14:58:44.062Z] Some errors have detailed explanations: E0308, E0605, E0609.

[2022-01-08T14:58:44.062Z] For more information about an error, try `rustc --explain E0308`.

[2022-01-08T14:58:44.062Z] error: could not compile `tikv_util` due to 4 previous errors
```

### What did happened?

seems introduced by https://github.com/tikv/tikv/pull/11785
@BusyJay PTAL
