### PR TITLE
Fix compile error in status server on MacOS

### LINKED ISSUE #11279: Compile error in status_server on Mac OS
### What version of TiKV are you using?

Master
### Steps to reproduce

run 
### What did you expect?

Everything goes OK

### What did happened?
```
error[E0061]: this function takes 6 arguments but 5 arguments were supplied
    --> src/server/status_server/mod.rs:1255:33
     |
1255 |         let mut status_server = StatusServer::new(
     |                                 ^^^^^^^^^^^^^^^^^ expected 6 arguments
1256 |             1,
     |             -
1257 |             None,
     |             ----
1258 |             ConfigController::default(),
     |             ---------------------------
1259 |             Arc::new(SecurityConfig::default()),
     |             -----------------------------------
1260 |             MockRouter,
     |             ---------- supplied 5 arguments
     |
note: associated function defined here
    --> src/server/status_server/mod.rs:94:12
     |
94   |     pub fn new(
     |            ^^^
95   |         status_thread_pool_size: usize,
     |         ------------------------------
96   |         pd_client: Option<Arc<RpcClient>>,
     |         ---------------------------------
97   |         cfg_controller: ConfigController,
     |         --------------------------------
98   |         security_config: Arc<SecurityConfig>,
     |         ------------------------------------
99   |         router: R,
     |         ---------
100  |         store_path: PathBuf,
     |         -------------------
```

This problem seems to be introduced by #11266

### PR DESCRIPTION
**Pull request by yuqi1129**
Signed-off-by: yuqi1129 <yuqi4733@gmail.com>

### What problem does this PR solve?

Issue Number: close #11279 

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

### Check List 

Tests 

- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

```release-note
 None
```

### CODE REVIEW

**Review by 5kbpers — APPROVED** [review]
LGTM, thanks!

**Review by youjiali1995 — APPROVED** [review]
How does it pass CI?🤨

**Comment by yuqi1129** [comment]
> How does it pass CI?🤨

Seems hard to test it in CI. CI runs on Linux platform, do you have any suggestion ?

**Comment by BusyJay** [comment]
Failpoint is always enabled in CI.
