### ISSUE TITLE
build: build failed on macOS

### ISSUE THREAD

**Issue by longfangsong** [tikv/tikv#9210]
## Development Task

Fix build failed under macOS, caused by #9206.

```
error[E0432]: unresolved import `crate::collections`
  --> components/tikv_util/src/metrics/threads_dummy.rs:12:12
   |
12 | use crate::collections::HashMap;
   |            ^^^^^^^^^^^
   |            |
   |            unresolved import
   |            help: a similar path exists: `std::collections`

error[E0432]: unresolved import `crate::collections`
  --> components/tikv_util/src/metrics/threads_dummy.rs:12:12
   |
12 | use crate::collections::HashMap;
   |            ^^^^^^^^^^^
   |            |
   |            unresolved import
   |            help: a similar path exists: `std::collections`

error: aborting due to previous error
```
