### ISSUE TITLE
Compilitaion and packaging issues on NIxOS

### ISSUE THREAD

**Issue by makuru-dd** [tikv/tikv#17098]
### What version of TiKV are you using?

Version 8.1.0

### What operating system and CPU are you using?

NixOS / Linux | x64

### Steps to reproduce

Build it with rustc version 1.77.2

### What did you expect?
That it compiles.

### What did happened?
```
warning: The interpretation of store paths arguments ending in `.drv` recently changed. If this command is now failing try again with '/nix/store/hx0ak1r4iakkq9xnw26ygbn63603ja4z-tikv-8.1.0.drv^*'
@nix { "action": "setPhase", "phase": "unpackPhase" }
Running phase: unpackPhase
unpacking source archive /nix/store/17piq70b24qrql63sijdi5273ghkmfyz-source
source root is source
Executing cargoSetupPostUnpackHook
Finished cargoSetupPostUnpackHook
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: patchPhase
Executing cargoSetupPostPatchHook
Validating consistency between /build/source/Cargo.lock and /build/cargo-vendor-dir/Cargo.lock
Finished cargoSetupPostPatchHook
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
Running phase: configurePhase
@nix { "action": "setPhase", "phase": "buildPhase" }
Running phase: buildPhase
Executing cargoBuildHook
++ env CC_X86_64_UNKNOWN_LINUX_GNU=/nix/store/9bv7dcvmfcjnmg5mnqwqlq2wxfn8d7yi-gcc-wrapper-13.2.0/bin/cc CXX_X86_64_UNKNOWN_LINUX_GNU=/nix/store/9bv7dcvmfc>
   Compiling libc v0.2.151
   Compiling proc-macro2 v1.0.76
   Compiling quote v1.0.28
   Compiling unicode-ident v1.0.5
   Compiling syn v1.0.103
   Compiling autocfg v1.1.0
   Compiling log v0.4.20
   Compiling cfg-if v1.0.0
   Compiling version_check v0.9.4
   Compiling serde_derive v1.0.147
   Compiling serde v1.0.147
   Compiling pkg-config v0.3.16
   Compiling memchr v2.7.1
   Compiling smallvec v1.11.1
   Compiling scopeguard v1.1.0
   Compiling once_cell v1.19.0
   Compiling lazy_static v1.4.0
   Compiling pin-project-lite v0.2.9
   Compiling futures-core v0.3.15
   Compiling lock_api v0.4.6
   Compiling futures-io v0.3.15
   Compiling slab v0.4.2
   Compiling proc-macro-hack v0.5.19
   Compiling futures v0.1.31
   Compiling futures-sink v0.3.15
   Compiling pin-utils v0.1.0
   Compiling proc-macro-nested v0.1.3
   Compiling futures-channel v0.3.15
   Compiling futures-task v0.3.15
   Compiling vcpkg v0.2.11
   Compiling parking_lot_core v0.9.1
   Compiling futures-macro v0.3.15
   Compiling futures-util v0.3.15
   Compiling itoa v1.0.1
   Compiling tokio v1.25.3
   Compiling bitflags v2.4.1
   Compiling unicode-segmentation v1.3.0
   Compiling itoa v0.4.4
   Compiling num-traits v0.2.17
   Compiling ryu v1.0.4
   Compiling fnv v1.0.6
   Compiling regex-syntax v0.8.2
   Compiling indexmap v1.6.2
   Compiling ahash v0.8.7
   Compiling tracing-core v0.1.32
   Compiling heck v0.3.1
   Compiling jobserver v0.1.17
   Compiling syn v2.0.43
   Compiling aho-corasick v1.1.2
   Compiling cfg-if v0.1.10
   Compiling openssl v0.10.57
   Compiling cc v1.0.83
   Compiling percent-encoding v2.1.0
   Compiling foreign-types-shared v0.1.1
   Compiling foreign-types v0.3.2
   Compiling hashbrown v0.9.1
   Compiling zerocopy v0.7.32
   Compiling protobuf v2.8.0 (https://github.com/pingcap/rust-protobuf?branch=v2.8#6642ebaa)
   Compiling allocator-api2 v0.2.14
   Compiling bytes v1.0.1
   Compiling matches v0.1.8
   Compiling hex v0.3.2
   Compiling httparse v1.8.0
   Compiling num_cpus v1.13.1
   Compiling signal-hook-registry v1.4.0
   Compiling mio v0.8.11
   Compiling socket2 v0.4.7
   Compiling getrandom v0.2.11
   Compiling parking_lot v0.12.1
   Compiling equivalent v1.0.1
   Compiling cmake v0.1.48 (https://github.com/rust-lang/cmake-rs#00e6b220)
   Compiling num-integer v0.1.45
   Compiling hashbrown v0.14.0
   Compiling try-lock v0.2.2
   Compiling want v0.3.0
   Compiling ppv-lite86 v0.2.10
   Compiling bitflags v1.3.2
   Compiling native-tls v0.2.7
   Compiling tower-service v0.3.2
   Compiling base64 v0.13.0
   Compiling crossbeam-utils v0.8.19
   Compiling httpdate v1.0.0
   Compiling form_urlencoded v1.0.1
   Compiling openssl-probe v0.1.2
   Compiling regex-automata v0.4.3
   Compiling serde_json v1.0.64
   Compiling autotools v0.2.6
   Compiling unicode-bidi v0.3.4
   Compiling unicode-normalization v0.1.12
   Compiling openssl-sys v0.9.92
   Compiling indexmap v2.0.1
   Compiling libz-sys v1.1.3
   Compiling protobuf-src v1.1.0+21.5
   Compiling rand_core v0.6.2
   Compiling time v0.1.43
   Compiling idna v0.2.0
   Compiling rand_chacha v0.3.0
   Compiling memoffset v0.6.4
   Compiling instant v0.1.12
   Compiling byteorder v1.4.3
   Compiling async-trait v0.1.58
   Compiling parking_lot_core v0.8.3
   Compiling ucd-trie v0.1.3
   Compiling rand v0.8.5
   Compiling pest v2.1.3
   Compiling parking_lot v0.11.1
   Compiling crossbeam-epoch v0.9.8
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling encoding_rs v0.8.33
   Compiling slog v2.5.2
   Compiling ipnet v2.3.0
   Compiling mime v0.3.16
   Compiling same-file v1.0.5
   Compiling walkdir v2.3.1
   Compiling dirs-sys-next v0.1.2
   Compiling dirs-next v2.0.0
   Compiling semver-parser v0.10.2
   Compiling grpcio-sys v0.10.3+1.44.0-patched
   Compiling static_assertions v1.1.0
   Compiling protobuf-codegen v2.8.0 (https://github.com/pingcap/rust-protobuf?branch=v2.8#6642ebaa)
   Compiling grpcio-compiler v0.10.4
   Compiling crc32fast v1.2.0
   Compiling regex v1.10.2
   Compiling hex v0.4.2
   Compiling atty v0.2.13
   Compiling crossbeam-deque v0.8.3
   Compiling semver v0.11.0
   Compiling fxhash v0.2.1
   Compiling crossbeam-channel v0.5.11
   Compiling rustc_version v0.3.3
   Compiling rayon-core v1.9.3
   Compiling zeroize v1.1.0
   Compiling shlex v0.1.1
   Compiling prometheus v0.13.0
   Compiling tikv_alloc v0.1.0 (/build/source/components/tikv_alloc)
   Compiling rayon v1.5.3
   Compiling thread_local v1.1.4
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> components/tikv_alloc/src/lib.rs:88:12
   |
88 | #![feature(core_intrinsics)]
   |            ^^^^^^^^^^^^^^^

   Compiling crossbeam-queue v0.3.5
For more information about this error, try `rustc --explain E0554`.
error: could not compile `tikv_alloc` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

**Comment by glorv** [comment]
@makuru-dd Seems nixos does not support the feature `core_intrinsics`.  Currnetly, we only build and test tikv for linux os, other os are not guaranteed to be compatible with all the code. Could you provide more details about you use case to running tikv on nixos.

I saw the `core_intrinsics` in introduced in #14866 in this case, Seems one easy workaround is to replace it with a normal atomic value like following:
```
#[repr(transparent)]
struct PeekableRemoteStat<T> {
   ptr: AtomicUsize,
   pathom: PhantomData<T>,
};

unsafe fn peek(&self) -> Option<T> {
        let ptr =  self.ptr.load(Ordering::SeqCst);
        if ptr == 0 {
            None
        } else {
            Some(ptr::read(ptr as *const T))
        }
    }
}
```

**Comment by makuru-dd** [comment]
> @makuru-dd Seems nixos does not support the feature `core_intrinsics`. Currnetly, we only build and test tikv for linux os, other os are not guaranteed to be compatible with all the code. Could you provide more details about you use case to running tikv on nixos.
> 
> I saw the `core_intrinsics` in introduced in #14866 in this case, Seems one easy workaround is to replace it with a normal atomic value like following:
> 
> ```
> #[repr(transparent)]
> struct PeekableRemoteStat<T> {
>    ptr: AtomicUsize,
>    pathom: PhantomData<T>,
> };
> 
> unsafe fn peek(&self) -> Option<T> {
>         let ptr =  self.ptr.load(Ordering::SeqCst);
>         if ptr == 0 {
>             None
>         } else {
>             Some(ptr::read(ptr as *const T))
>         }
>     }
> }
> ```

> Could you provide more details about you use case to running tikv on nixos.

Hi I am trying to build TIKV for [NixOS](https://nixos.org/) / linux to add it to [MicroVM.nix](https://github.com/astro/microvm.nix), so I can use it as a key value back end for [seaweedfs](https://github.com/seaweedfs/seaweedfs), A distributed Filesystem instead of ceph, I need seaweedFS for storage of each VM.

> Seems nixos does not support the feature core_intrinsics

I have solved that problem by making a NixOS flake, this allows me to use `Rustc` Unstable, which seems to have `core_intrinsics`, sadly I cant push it up in to the package repository of NixOS.
Now I am a stuck at errors relating to rocksdb, where I am missing certain files, that don't get imported, properly.
It would be nice, if you could help me with it.
Here are the logs.
https://0x0.st/Xc2A.log

**Comment by v01dstar** [comment]
``` nowrap
/nix/store/9bv7dcvmfcjnmg5mnqwqlq2wxfn8d7yi-gcc-wrapper-13.2.0/bin/c++ ... -I/build/cargo-vendor-dir/libtitan_sys-0.0.1/../rocksdb -I/build/cargo-vendor-dir/libtitan_sys-0.0.1/../rocksdb/include ... -c /build/cargo-vendor-dir/libtitan_sys-0.0.1/titan/src/blob_file_reader.cc
```
The compiler was expecting those header files under `-I/build/cargo-vendor-dir/libtitan_sys-0.0.1/../rocksdb`, can you please check whether they are there?

**Comment by makuru-dd** [comment]
> ```
> /nix/store/9bv7dcvmfcjnmg5mnqwqlq2wxfn8d7yi-gcc-wrapper-13.2.0/bin/c++ ... -I/build/cargo-vendor-dir/libtitan_sys-0.0.1/../rocksdb -I/build/cargo-vendor-dir/libtitan_sys-0.0.1/../rocksdb/include ... -c /build/cargo-vendor-dir/libtitan_sys-0.0.1/titan/src/blob_file_reader.cc
> ```
> 
> The compiler was expecting those header files under `-I/build/cargo-vendor-dir/libtitan_sys-0.0.1/../rocksdb`, can you please check whether they are there?

So, I checked and no, the are not there but `rocksdb-0.3.0` is there.
Maybe it can't pull the git repo?

**Comment by kvtb** [comment]
It is better to pin exact rustc version from https://github.com/tikv/tikv/blob/v8.1.0/rust-toolchain.toml https://github.com/tikv/tikv/blob/v7.5.2/rust-toolchain than NixOS default.

Or you will have to invent new patches on every update of NixOS's default Rust

**Comment by makuru-dd** [comment]
I already pinned it.

**Comment by v01dstar** [comment]
I was on vacation for 2 weeks, have you resolved the issue? Feels to me, it is related to how you organize the dependencies. Do you use "vendored" sources? If so, have you imported the submodules when you download rust-rocksdb? `git submodule update --init --recursive` https://github.com/tikv/rust-rocksdb?tab=readme-ov-file#build

**Comment by makuru-org** [comment]
So it seems that the build script of titian seems to expect at `rocksdb/` but it's at `rocksdb-0.3.0/` and if it doesn't find it, i think it wants to use git to pull it from the internet, which doesn't work.
