### PR TITLE
*: Fix build on MacOS 15.4 with Apple clang v17.0.0

### LINKED ISSUE #17962: Compile failed on my MacM2Max
### What version of TiKV are you using?
I built TiKV from source code with tag release-8.5.

### What operating system and CPU are you using?
MacOS 14.7.1 (23H222)

### Steps to reproduce
just execute `make` command.

### What did you expect?
build success.

### What did happened?
build failed with these outputs.
It seems build failed because of a macro in ZLIB dependency.
cargo:warning=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_stdio.h:314:7: error: expected ')'

  cargo:warning=  314 | FILE    *fdopen(int, const char *) __DARWIN_ALIAS_STARTING(__MAC_10_6, __IPHONE_2_0, __DARWIN_ALIAS(fdopen));

  cargo:warning=      |          ^

  cargo:warning=src/zlib/zutil.h:140:33: note: expanded from macro 'fdopen'

  cargo:warning=  140 | #        define fdopen(fd,mode) NULL /* No fdopen() */

  cargo:warning=      |                                 ^

  cargo:warning=/opt/homebrew/Cellar/llvm/19.1.3/lib/clang/19/include/__stddef_null.h:26:22: note: expanded from macro 'NULL'

  cargo:warning=   26 | #define NULL ((void*)0)

  cargo:warning=      |                      ^

  cargo:warning=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_stdio.h:314:7: note: to match this '('

  cargo:warning=src/zlib/zutil.h:140:33: note: expanded from macro 'fdopen'

  cargo:warning=  140 | #        define fdopen(fd,mode) NULL /* No fdopen() */

  cargo:warning=      |                                 ^

  cargo:warning=/opt/homebrew/Cellar/llvm/19.1.3/lib/clang/19/include/__stddef_null.h:26:14: note: expanded from macro 'NULL'

  cargo:warning=   26 | #define NULL ((void*)0)

  cargo:warning=      |              ^

  cargo:warning=21 warnings generated.

### LINKED ISSUE #18353: Build failed after upgrading to clang 17
MacOS upgrade clang from 16 -> 17.

TiKV's dependencies kvproto -> grpc-rs fail to build with clang 17

### LINKED ISSUE #18357: "rust-rocksdb" build failed on MacOS 15.4 with clang v17.0.0
### What version of TiKV are you using?

master (3eb3439fd88f0db9de06ef92e845e80b32c9b49a)

### What operating system and CPU are you using?

```
❯ uname -a
Darwin x.x.x.x 24.4.0 Darwin Kernel Version 24.4.0: Wed Mar 19 21:18:00 PDT 2025; root:xnu-11417.101.15~1/RELEASE_ARM64_T8122 arm64
❯ clang --version
Apple clang version 17.0.0 (clang-1700.0.13.3)
Target: arm64-apple-darwin24.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

### Steps to reproduce

Build with `make build`.

### What did you expect?

Build succeed.

### What did happened?

Build failed:

```
❯ make clean build
...
...
     Called from: [1]	/Users/pingyu/.cargo/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/56f3a91/librocksdb_sys/rocksdb/tools/CMakeLists.txt
  make[1]: warning: -jN forced in submake: disabling jobserver mode.
  /Users/pingyu/.cargo/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/56f3a91/librocksdb_sys/rocksdb/encryption/encryption.cc:96:20: error: variable length arrays in C++ are a Clang extension [-Werror,-Wvla-cxx-extension]
     96 |   unsigned char iv[block_size];
        |                    ^~~~~~~~~~
  /Users/pingyu/.cargo/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/56f3a91/librocksdb_sys/rocksdb/encryption/encryption.cc:96:20: note: initializer of 'block_size' is not a constant expression
  /Users/pingyu/.cargo/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/56f3a91/librocksdb_sys/rocksdb/encryption/encryption.cc:80:16: note: declared here
     80 |   const size_t block_size = BlockSize();
        |                ^
  /Users/pingyu/.cargo/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/56f3a91/librocksdb_sys/rocksdb/encryption/encryption.cc:118:31: error: variable length arrays in C++ are a Clang extension [-Werror,-Wvla-cxx-extension]
    118 |   unsigned char partial_block[block_size];
        |                               ^~~~~~~~~~
  /Users/pingyu/.cargo/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/56f3a91/librocksdb_sys/rocksdb/encryption/encryption.cc:118:31: note: initializer of 'block_size' is not a constant expression
  /Users/pingyu/.cargo/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/56f3a91/librocksdb_sys/rocksdb/encryption/encryption.cc:80:16: note: declared here
     80 |   const size_t block_size = BlockSize();
        |                ^
  2 errors generated.
  make[4]: *** [CMakeFiles/rocksdb.dir/encryption/encryption.cc.o] Error 1
  make[4]: *** Waiting for unfinished jobs....
  make[3]: *** [CMakeFiles/rocksdb.dir/all] Error 2
  make[2]: *** [CMakeFiles/rocksdb.dir/rule] Error 2
  make[1]: *** [rocksdb] Error 2
  thread 'main' panicked at /Users/pingyu/.cargo/git/checkouts/cmake-rs-1b5303aca42ae56b/00e6b22/src/lib.rs:1054:5:

  command did not execute successfully, got: exit status: 2

  build script failed, must exit now
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
make: *** [build] Error 101
```

### PR DESCRIPTION
**Pull request by pingyu**
### What is changed and how it works?

Issue Number: ref #17962, ref #18353, ref #18357

What's Changed:

```commit-message
*: Fix build on MacOS 15.4 with Apple clang v17.0.0
```

- Upgrade `libz-sys` to fix #17962
- Upgrade `cmake-rs` to fix #18353
- Add `-Wno-error=vla -Wno-vla-extension` to `CFLAGS` & `CXXFLAGS` to disable `-Werror` and enable ` VLAs` for RocksDB build to fix #18357 

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

```
❯ make clean build
    ...
    ...
    Finished dev [unoptimized] target(s) in 5m 50s
warning: the following packages contain code that will be rejected by a future version of Rust: fs_extra v1.1.0, nom v5.1.0, quick-xml v0.22.0
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
❯
```

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
*: Fix build on MacOS 15.4 with Apple clang v17.0.0
```

### CODE REVIEW

**Review by v01dstar — APPROVED** [review]
Can you "ref" the bugs, instead of closing them? I am planning to fix them permanently by refactoring the code. Code that triggers the compilation warnings are owned by us.

**Comment by pingyu** [comment]
> Can you "ref" the bugs, instead of closing them? I am planning to fix them permanently by refactoring the code. Code that triggers the compilation warnings are owned by us.

Sure. Done~

**Review by YuJuncen — APPROVED** [review]

File: Cargo.lock [hunk 1]
```diff
@@ -4564,18 +4563,18 @@ checksum = "77af24da69f9d9341038eba93a073b1fdaaa1b788221b00a69bce9e762cb32de"
 
 [[package]]
 name = "openssl-src"
-version = "111.25.0+1.1.1t"
+version = "300.4.2+3.4.1"
```
Comment (overvenus) [inline Cargo.lock:4566]: This upgrades OpenSSL to v3.4.1, you need to evaluate its performance and FIPS requirements.

Comment (pingyu) [reply Cargo.lock:4566]: Fixed by #18362
