### ISSUE TITLE
tikv build fail on darwin

### ISSUE THREAD

**Issue by zhouqiang-cl** [tikv/tikv#11698]
## Bug Report

```
[2021-12-21T17:57:18.712Z] error[E0432]: unresolved import `nix::unistd::gettid`

[2021-12-21T17:57:18.712Z]   --> components/file_system/src/thread_io.rs:15:27

[2021-12-21T17:57:18.712Z]    |

[2021-12-21T17:57:18.712Z] 15 | use nix::unistd::{getpid, gettid, Pid};

[2021-12-21T17:57:18.712Z]    |                           ^^^^^^

[2021-12-21T17:57:18.712Z]    |                           |

[2021-12-21T17:57:18.712Z]    |                           no `gettid` in `unistd`

[2021-12-21T17:57:18.713Z]    |                           help: a similar name exists in the module: `getpid`
```

### What operating system and CPU are you using?

master

**Comment by zhouqiang-cl** [comment]
caused by https://github.com/tikv/tikv/pull/11667/files

**Comment by yuqi1129** [comment]
+1, Master branch can't be debugged on darwin OS now 🥲

**Comment by zhouqiang-cl** [comment]
@MuZhou233 could please take a look?
