### PR TITLE
build: fix building under macos

### LINKED ISSUE #9210: build: build failed on macOS
## Development Task

Fix build failed under macOS, caused by #9206.

```
error[E0432]: unresolved import `crate::collections`
  --> components/tikv_util/src/metrics/threads_dummy.rs:12:12
   |
12 | use crate::collections::HashMap;
   |            ^^^^^^^^^^^
   |            |
   |            unresolved import
   |            help: a similar path exists: `std::collections`

error[E0432]: unresolved import `crate::collections`
  --> components/tikv_util/src/metrics/threads_dummy.rs:12:12
   |
12 | use crate::collections::HashMap;
   |            ^^^^^^^^^^^
   |            |
   |            unresolved import
   |            help: a similar path exists: `std::collections`

error: aborting due to previous error
```

### PR DESCRIPTION
**Pull request by longfangsong**
Signed-off-by: longfangsong <longfangsong@icloud.com>

### What problem does this PR solve?

Issue Number: close #9210

Problem Summary: Failed to build master under macOS

### What is changed and how it works?

What's Changed:

Just use `collections::HashMap` instead of `crate::collections::HashMap` in `threads_dummy.rs`.

### Check List 

Tests 

- No code

### CODE REVIEW

**Comment by longfangsong** [comment]
@Connor1996 PTAL

**Review by youjiali1995 — COMMENTED** [review]
lgtm

**Comment by longfangsong** [comment]
Since many our developers are using macOS.
Shall we prevent building errors on macOS happen again by let the ci check whether it can build under macOS? 
I think GitHub actions can do this.

**Comment by youjiali1995** [comment]
> Since many our developers are using macOS, shall we prevent building errors on macOS happen again by let the ci check whether it can build under macOS?
> I think GitHub actions can do this. The only problem is the compile time might be too long ...

Seems we don't have macOS to do it.

**Comment by longfangsong** [comment]
> Seems we don't have macOS to do it.

I tried GitHub actions [here](https://github.com/tikv/tikv/compare/master...longfangsong:os-check):
图片

The only problem is GitHub actions' building time is a little too long and unstable, normally our CI runs for only  15min.
I'll send a [pr](https://github.com/tikv/tikv/pull/9219) anyway.

**Review by ti-srebot — APPROVED** [review]

**Comment by sticnarf** [comment]
> > Seems we don't have macOS to do it.
> 
> I tried GitHub actions [here](https://github.com/tikv/tikv/compare/master...longfangsong:os-check):
> 图片
> 
> The only problem is GitHub actions' building time is a little too long and unstable, normally our CI runs for only 15min.
> I'll send a [pr](https://github.com/tikv/tikv/pull/9219) anyway.

@longfangsong Let's merge it and see if the github action in that PR passes.

15 minutes seems too long. We can try to cache something.

**Review by Connor1996 — APPROVED** [review]
