### ISSUE TITLE
release-6.1: make format fails due to cargo-sort version incompatibility

### ISSUE THREAD

**Issue by lybcodes** [tikv/tikv#19232]
### What version of TiKV are you using?
**Branch:** `release-6.1`
**rust-toolchain.toml:**
```toml
[toolchain]
channel = "nightly-2022-02-14"
```
**Makefile pre-format target:**
```makefile
pre-format: unset-override
	@rustup component add rustfmt
	@cargo install -q cargo-sort 
```

### What operating system and CPU are you using?
- **OS:** Linux (in CI environment)
- **Architecture:** x86_64
- **CI Image:** `hub.pingcap.net/jenkins/tikv-cached-release-6.1:latest`

### Steps to reproduce
1. Checkout release-6.1 branch
2. Run `make format`
3. The command fails with compilation error

**Reproduction command:**
```bash
cd tikv-src
export RUSTFLAGS=-Dwarnings
make format
```

### What did you expect?
`make format` should complete successfully, similar to how it works in release-6.5 branch or other target branches.

### What did happened?
`make format` fails with the following error:
```
error: failed to compile `cargo-sort v2.0.2`, intermediate artifacts can be found at `/tmp/cargo-install3Q9266`

Caused by:
  package `rustix v1.1.2` cannot be built because it requires rustc 1.63 or newer, 
  while the currently active rustc version is 1.60.0-nightly

make: *** [pre-format] Error 101
```
### Root Cause Analysis and My Personal Suggestions
1. **rust-toolchain.toml** specifies `nightly-2022-02-14` (rustc 1.60.0)
2. **Makefile pre-format target** executes `cargo install -q cargo-sort` without version check
3. `cargo install` attempts to install the latest version `cargo-sort v2.0.2`
4. `cargo-sort v2.0.2` requires rustc 1.66+ (dependency `rustix v1.1.2` requires rustc 1.63+)
5. Current toolchain is rustc 1.60.0 → compilation fails

#### Comparison with Other Branches

**release-6.5 branch** (works correctly):
- Makefile has check: `@which cargo-sort &> /dev/null || cargo install -q cargo-sort`
- If `cargo-sort` is already installed (e.g., the base image has installed v1.0.9 ), it skips installation 
- Uses the pre-installed compatible version

**release-6.1 branch** (fails):
- Makefile has no check: `@cargo install -q cargo-sort`
- Always attempts to install latest version (v2.0.2) 
- Fails due to version incompatibility 

#### My personal view on potential solutions
Solution 1: Modify Makefile ：Add version check in `pre-format` target, similar to other branches（Since version 1.0.9 is already installed in the base image, adding a version check will prevent the latest version from being installed）:
```makefile
pre-format: unset-override
	@rustup component add rustfmt
	@which cargo-sort &> /dev/null || cargo install -q cargo-sort
```

#### Failed CI test for release-6.1
- https://do.pingcap.net/jenkins/blue/organizations/jenkins/tikv%2Ftikv%2Frelease-6.1%2Fpull_unit_test/detail/pull_unit_test/29/pipeline/
#### Comparison with release-6.5
- https://do.pingcap.net/jenkins/blue/organizations/jenkins/tikv%2Ftikv%2Frelease-6.5%2Fpull_unit_test/detail/pull_unit_test/169/pipeline/57/

**Comment by lybcodes** [comment]
@LykxSassinator Hi, this issue affects the `make format` command in release-6.1 branch. Could you please take a look?Thanks!

**Comment by LykxSassinator** [comment]
The default installation version of `cargo-sort` is too new for the stale branch `release-6.1`. And you can use `--version 1.0.9` to replace the original script, just like:

```
@which cargo-sort &> /dev/null || cargo install -q cargo-sort --version 1.0.9
```

**Comment by lybcodes** [comment]
The maintenance cycle for release-6.1 has ended.（https://www.pingcap.com/tidb-release-support-policy/）
